item1 = input("Enter first grocery item: ")
item2 = input("Enter second grocery item:")
item3 = input("Enter third grocery item:")
item4 = input("Enter fourth grocery item:")
print(f"Your shopping list:{item1},{item2},{item3},{item4}")
